CI/QA: introduce Composer, update test suite (#109)
* Introduce a `composer.json` configuration file

This will allow for this package to be listed on Packagist, but more than anything, documents the development dependencies of the plugin.

* Move the `require-dev` statements from the GH Actions workflows to the `composer.json` file.
* Git ignore the `composer.lock` file and the `vendor` directory.
* Export ignore the `composer.json` file as there are only dev dependencies and Composer is not used for autoloading.

* Tests: update for WP Core test changes

Composer:
* Add dependency on the PHPUnit Polyfills

Test config:
* Make the PHPUnit behaviour consistent across different versions by fixing a particular directive.

Test bootstrap:
* Load the PHPUnit Polyfills autoloader before running the WP native bootstrap file.

In the tests:
* Use `snake_case` fixture method names.
* Update assertions to modern PHPUnit where relevant.

* GH Actions: update for WP Core test changes

* Remove the PHPUnit requirement depending on the WP version being tested against.
* Toggle how the `composer install` is run depending on the PHP and the WP version being tested against.
* Add build against PHP 8.1 (allowed to fail for now).
* Add some extra builds for interim WP versions.

* Tests: sync with WP Core

Sync in the comment improvements which were made in the WP Core tests for the same.

Co-authored-by: jrfnl <jrfnl@users.noreply.github.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -51,8 +51,17 @@ jobs:
           - php: '5.6'
             wp: '5.5'
             experimental: false
+          - php: '7.2'
+            wp: '5.7'
+            experimental: false
+          - php: '7.0'
+            wp: '5.8'
+            experimental: false
 
           # Experimental builds. These are allowed to fail.
+          - php: '8.1'
+            wp: 'trunk'
+            experimental: true
           - php: '7.4'
             wp: 'trunk'
             experimental: true
@@ -91,29 +100,22 @@ jobs:
       - name: Set up WordPress
         run: phpunit/install.sh wordpress_test root '' 127.0.0.1:3306 ${{ matrix.wp }}
 
-      # On WP 5.2, PHPUnit 5.x, 6.x and 7.x are supported.
-      # On PHP >= 8.0, PHPUnit 7.5+ is needed, no matter what.
-      - name: Determine supported PHPUnit version
-        id: set_phpunit
-        run: |
-          if [[ "${{ matrix.php }}" > "7.4" ]]; then
-            echo '::set-output name=PHPUNIT::7.5.*'
-          else
-            echo '::set-output name=PHPUNIT::5.7.*||6.5.*||7.5.*'
-          fi
-
-      - name: 'Composer: set up PHPUnit'
-        run: composer require --no-update phpunit/phpunit:"${{ steps.set_phpunit.outputs.PHPUNIT }}"
+      # Remove the PHPUnit requirement for WP 5.9 and higher in favour of letting the Polyfills manage it.
+      # The Composer command will exit with error code 2 as the package is not removed, so ignore "failure" of this step.
+      - name: Conditionally remove PHPUnit requirement
+        if: ${{ ( matrix.wp == 'trunk' || matrix.wp >= 5.9 ) && matrix.wp != 'latest' }}
+        continue-on-error: true
+        run: composer remove --dev phpunit/phpunit --no-update || true
 
       # Install dependencies and handle caching in one go.
       # @link https://github.com/marketplace/actions/install-composer-dependencies
       - name: Install Composer dependencies for PHP < 8.0
-        if: ${{ matrix.php < 8.0 }}
+        if: ${{ matrix.php < 8.0 || ( ( matrix.wp == 'trunk' || matrix.wp >= 5.9 ) && matrix.wp != 'latest' ) }}
         uses: "ramsey/composer-install@v1"
 
-      # For the PHP 8.0 and above, we need to install with ignore platform reqs as not all dependencies allow it yet.
+      # For PHP 8.0 and above on WP 5.2 - 5.8, we need to install with ignore platform reqs as not all dependencies allow it.
       - name: Install Composer dependencies for PHP >= 8.0
-        if: ${{ matrix.php >= 8.0 }}
+        if: ${{ matrix.php >= 8.0 && ( matrix.wp == 'latest' || ( matrix.wp != 'trunk' && matrix.wp < 5.9 ) ) }}
         uses: "ramsey/composer-install@v1"
         with:
           composer-options: --ignore-platform-reqs
